name: wip

services:

  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    #      target: production
    volumes:
      - .:/var/www/html
      - ./app-web-volume:/var/www/app-web
    tty: true
    ports:
      - 80:80
